const products = [
  {
    id: 'b1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Books',
    subcategory: 'Fiction',
    price: 499,
    originalPrice: 699,
    discount: 28,
    rating: 4.7,
    reviews: 342,
    isbn: '978-0743273565',
    publisher: 'Scribner',
    language: 'English',
    pages: 180,
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. A classic tale of the American Dream in the Roaring Twenties.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800',
    stock: 15,
    featured: true,
    newArrival: false
  },
  {
    id: 'b2',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    category: 'Books',
    subcategory: 'Non-Fiction',
    price: 650,
    originalPrice: 899,
    discount: 27,
    rating: 4.8,
    reviews: 1245,
    isbn: '978-0062316097',
    publisher: 'Harper',
    language: 'English',
    pages: 464,
    description: '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance?',
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800',
    stock: 42,
    featured: true,
    newArrival: false
  },
  {
    id: 'b3',
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Books',
    subcategory: 'Non-Fiction',
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviews: 4502,
    isbn: '978-0735211292',
    publisher: 'Avery',
    language: 'English',
    pages: 320,
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear reveals practical strategies to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    image: 'https://images.unsplash.com/photo-1589998059171-989d887dda19?auto=format&fit=crop&q=80&w=800',
    stock: 120,
    featured: true,
    newArrival: true
  },
  {
    id: 'b4',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    category: 'Books',
    subcategory: 'Fiction',
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.6,
    reviews: 893,
    isbn: '978-0062315007',
    publisher: 'HarperOne',
    language: 'English',
    pages: 208,
    description: 'Paulo Coelho\'s masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800',
    stock: 8,
    featured: false,
    newArrival: false
  },
  {
    id: 'b5',
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Héctor García',
    category: 'Books',
    subcategory: 'Non-Fiction',
    price: 450,
    originalPrice: 550,
    discount: 18,
    rating: 4.7,
    reviews: 2100,
    isbn: '978-0143130727',
    publisher: 'Penguin Books',
    language: 'English',
    pages: 208,
    description: 'Bring meaning and joy to all your days with this internationally bestselling guide to the Japanese concept of ikigai.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800',
    stock: 34,
    featured: false,
    newArrival: true
  },
  {
    id: 's1',
    title: 'Premium Leather Journal',
    author: 'BookNook Studio',
    category: 'Stationery',
    subcategory: 'Notebooks',
    price: 899,
    originalPrice: 1200,
    discount: 25,
    rating: 4.9,
    reviews: 142,
    isbn: 'N/A',
    publisher: 'N/A',
    language: 'N/A',
    pages: 240,
    description: 'A beautiful handcrafted leather journal with 120gsm dotted pages, perfect for bullet journaling, sketching, or capturing your thoughts.',
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&q=80&w=800',
    stock: 50,
    featured: true,
    newArrival: false
  },
  {
    id: 'b6',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    category: 'Books',
    subcategory: 'Children',
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviews: 8032,
    isbn: '978-0590353427',
    publisher: 'Scholastic',
    language: 'English',
    pages: 309,
    description: 'Harry Potter has never played a sport while flying on a broomstick. He\'s never worn a cloak of invisibility, befriended a giant, or helped hatch a dragon...',
    image: 'https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800',
    stock: 25,
    featured: false,
    newArrival: false
  },
  {
    id: 'b7',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    category: 'Books',
    subcategory: 'Fiction',
    price: 550,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 3210,
    isbn: '978-0345339683',
    publisher: 'Del Rey',
    language: 'English',
    pages: 320,
    description: 'A great modern classic and the prelude to The Lord of the Rings. Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar.',
    image: 'https://images.unsplash.com/photo-1629196914271-92be344d9522?auto=format&fit=crop&q=80&w=800',
    stock: 12,
    featured: true,
    newArrival: false
  },
  {
    id: 's2',
    title: 'Minimalist Fountain Pen',
    author: 'Crafted Ink',
    category: 'Stationery',
    subcategory: 'Pens',
    price: 1299,
    originalPrice: 1599,
    discount: 18,
    rating: 4.5,
    reviews: 86,
    isbn: 'N/A',
    publisher: 'N/A',
    language: 'N/A',
    pages: 0,
    description: 'An elegantly designed fountain pen with a smooth medium nib. Includes a converter and 2 blue ink cartridges. Perfect for writers and professionals.',
    image: 'https://images.unsplash.com/photo-1527010154944-f2241763d806?auto=format&fit=crop&q=80&w=800',
    stock: 20,
    featured: true,
    newArrival: true
  },
  {
    id: 'b8',
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    category: 'Books',
    subcategory: 'Non-Fiction',
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.6,
    reviews: 5120,
    isbn: '978-1612680194',
    publisher: 'Plata Publishing',
    language: 'English',
    pages: 336,
    description: 'Rich Dad Poor Dad is Robert\'s story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing.',
    image: 'https://images.unsplash.com/photo-1554774853-719586f82d77?auto=format&fit=crop&q=80&w=800',
    stock: 65,
    featured: false,
    newArrival: false
  },
  {
    id: 'b9',
    title: '1984',
    author: 'George Orwell',
    category: 'Books',
    subcategory: 'Fiction',
    price: 250,
    originalPrice: 350,
    discount: 28,
    rating: 4.7,
    reviews: 6420,
    isbn: '978-0451524935',
    publisher: 'Signet Classic',
    language: 'English',
    pages: 328,
    description: 'Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real.',
    image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&q=80&w=800',
    stock: 45,
    featured: false,
    newArrival: false
  },
  {
    id: 'b10',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    category: 'Books',
    subcategory: 'Fiction',
    price: 199,
    originalPrice: 299,
    discount: 33,
    rating: 4.8,
    reviews: 4310,
    isbn: '978-0141439518',
    publisher: 'Penguin Classics',
    language: 'English',
    pages: 480,
    description: 'Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen\'s beloved classic.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800',
    stock: 18,
    featured: false,
    newArrival: true
  },
  {
    id: 's3',
    title: 'Watercolor Paint Set',
    author: 'Artisan Colors',
    category: 'Stationery',
    subcategory: 'Art Supplies',
    price: 1450,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviews: 215,
    isbn: 'N/A',
    publisher: 'N/A',
    language: 'N/A',
    pages: 0,
    description: 'Professional grade watercolor set featuring 24 highly pigmented half-pans in a compact metal tin with a mixing palette.',
    image: 'https://images.unsplash.com/photo-1560780552-ba54683cb263?auto=format&fit=crop&q=80&w=800',
    stock: 15,
    featured: false,
    newArrival: false
  },
  {
    id: 'b11',
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    category: 'Books',
    subcategory: 'Children',
    price: 499,
    originalPrice: 599,
    discount: 16,
    rating: 4.9,
    reviews: 1205,
    isbn: '978-0060254926',
    publisher: 'HarperCollins',
    language: 'English',
    pages: 48,
    description: 'Maurice Sendak\'s Caldecott Medal-winning picture book has become one of the most highly acclaimed and best-loved children\'s books of all time.',
    image: 'https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800',
    stock: 30,
    featured: false,
    newArrival: true
  },
  {
    id: 'b12',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    category: 'Books',
    subcategory: 'Non-Fiction',
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.6,
    reviews: 3102,
    isbn: '978-0374533557',
    publisher: 'Farrar, Straus and Giroux',
    language: 'English',
    pages: 499,
    description: 'The phenomenal New York Times Bestseller by Nobel Prize winner Daniel Kahneman, explaining the two systems that drive the way we think.',
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800',
    stock: 22,
    featured: false,
    newArrival: false
  },
  {
    id: 's4',
    title: 'Brass Desk Organizer',
    author: 'BookNook Studio',
    category: 'Stationery',
    subcategory: 'Desk Accessories',
    price: 1899,
    originalPrice: 2200,
    discount: 13,
    rating: 4.8,
    reviews: 64,
    isbn: 'N/A',
    publisher: 'N/A',
    language: 'N/A',
    pages: 0,
    description: 'Keep your workspace tidy with this elegant solid brass desk organizer. Heavyweight, non-slip base with compartments for pens, paperclips, and cards.',
    image: 'https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?auto=format&fit=crop&q=80&w=800',
    stock: 5,
    featured: true,
    newArrival: true
  },
  {
    id: 'b13',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    category: 'Books',
    subcategory: 'Fiction',
    price: 450,
    originalPrice: 599,
    discount: 24,
    rating: 4.5,
    reviews: 8432,
    isbn: '978-0525559474',
    publisher: 'Viking',
    language: 'English',
    pages: 304,
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800',
    stock: 40,
    featured: false,
    newArrival: false
  },
  {
    id: 'b14',
    title: 'Dune',
    author: 'Frank Herbert',
    category: 'Books',
    subcategory: 'Fiction',
    price: 699,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 9540,
    isbn: '978-0441172719',
    publisher: 'Ace Books',
    language: 'English',
    pages: 412,
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800',
    stock: 15,
    featured: false,
    newArrival: false
  },
  {
    id: 's5',
    title: 'Calligraphy Starter Kit',
    author: 'Artisan Colors',
    category: 'Stationery',
    subcategory: 'Gift Sets',
    price: 2499,
    originalPrice: 2999,
    discount: 16,
    rating: 4.9,
    reviews: 112,
    isbn: 'N/A',
    publisher: 'N/A',
    language: 'N/A',
    pages: 0,
    description: 'Everything you need to begin your calligraphy journey. Includes 2 wooden nib holders, 5 assorted nibs, 3 bottles of premium ink, and a practice pad.',
    image: 'https://images.unsplash.com/photo-1527010154944-f2241763d806?auto=format&fit=crop&q=80&w=800',
    stock: 10,
    featured: false,
    newArrival: true
  },
  {
    id: 'b15',
    title: 'Goodnight Moon',
    author: 'Margaret Wise Brown',
    category: 'Books',
    subcategory: 'Children',
    price: 350,
    originalPrice: 450,
    discount: 22,
    rating: 4.9,
    reviews: 2154,
    isbn: '978-0060775858',
    publisher: 'HarperFestival',
    language: 'English',
    pages: 32,
    description: 'In a great green room, tucked away in bed, is a little bunny. "Goodnight room, goodnight moon." And to all the familiar things in the softly lit room.',
    image: 'https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800',
    stock: 28,
    featured: false,
    newArrival: false
  }
];

// Helper functions for data access
const getProductById = (id) => products.find(p => p.id === id);
const getProductsByCategory = (category) => products.filter(p => p.category.toLowerCase() === category.toLowerCase());
const getFeaturedProducts = () => products.filter(p => p.featured);
const getNewArrivals = () => products.filter(p => p.newArrival);
const searchProducts = (query) => {
  const q = query.toLowerCase();
  return products.filter(p => 
    p.title.toLowerCase().includes(q) || 
    p.author.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.isbn.includes(q)
  );
};
